# This is an auto-generated stub file for cocotb testbench
# Generated by copra
"""Auto-generated type stubs for cocotb DUT."""

from cocotb.handle import (
    HierarchyObject,
)

class Minimal(HierarchyObject):
    """Auto-generated class for Minimal."""

    clk: HierarchyObject
    data_in: HierarchyObject
    data_out: HierarchyObject
    minimal: HierarchyObject
    rst_n: HierarchyObject

# Type alias for the main DUT
DutType = Minimal
