# This is an auto-generated stub file for cocotb testbench
# Generated by copra
"""Auto-generated type stubs for cocotb DUT."""

from cocotb.handle import (
    HierarchyObject,
    SimHandleBase,
)

class Minimal(HierarchyObject):
    """Auto-generated class for Minimal.

    This class provides typed access to the DUT hierarchy,
    enabling IDE autocompletion and static type checking.

    Signals:
        clk: SimHandleBase
        data_in: SimHandleBase
        data_out: SimHandleBase
        minimal: SimHandleBase
        rst_n: SimHandleBase

    """

    # Signal attributes
    clk: SimHandleBase
    data_in: SimHandleBase
    data_out: SimHandleBase
    minimal: SimHandleBase
    rst_n: SimHandleBase

# Type alias for the main DUT
DutType = Minimal
