# This is an auto-generated stub file for cocotb testbench
# Generated by copra v0.1.0 at 2025-06-01 08:21:29
# Template: default
"""Auto-generated type stubs for cocotb DUT.

This file provides type hints for IDE autocompletion and static type checking.
Generated from DUT hierarchy analysis using copra.

Usage:
    from typing import cast
    from minimal import DutType

    @cocotb.test()
    async def test_example(dut):
        typed_dut = cast(DutType, dut)
        # Now you have full IDE support for dut.signal_name
"""

from cocotb.handle import (
    HierarchyObject,
    SimHandleBase,
)

class Minimal(HierarchyObject):
    """Type stub for minimal module.

    This class provides type hints for the top-level DUT.

    Top-level signals: 4
    Sub-modules: 0
    """

    clk: SimHandleBase  # Signal in minimal: clk
    data_in: SimHandleBase  # Signal in minimal: data_in
    data_out: SimHandleBase  # Signal in minimal: data_out
    rst_n: SimHandleBase  # Signal in minimal: rst_n


# Type alias for the main DUT
DutType = Minimal
