from __future__ import annotations
import cocotb.handle
import cocotb.types

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class DUT(cocotb.handle.HierarchyObject):
    in_2d_arr: cocotb.handle.LogicArrayObject
    in_2d_arr_packed: cocotb.handle.LogicArrayObject
    in_2d_arr_unpacked: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    in_2d_vect_packed_packed: cocotb.handle.LogicArrayObject
    in_2d_vect_packed_unpacked: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    in_2d_vect_unpacked_unpacked: cocotb.handle.ArrayObject[cocotb.types.Array[cocotb.types.Logic], cocotb.handle.ArrayObject[cocotb.types.Logic, cocotb.handle.LogicObject]]
    in_3d_arr: cocotb.handle.LogicArrayObject
    in_arr: cocotb.handle.LogicArrayObject
    in_arr_packed: cocotb.handle.LogicArrayObject
    in_arr_packed_packed: cocotb.handle.LogicArrayObject
    in_arr_packed_unpacked: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    in_arr_unpacked: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    in_arr_unpacked_unpacked: cocotb.handle.ArrayObject[cocotb.types.Array[cocotb.types.LogicArray], cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]]
    in_vect_packed: cocotb.handle.LogicArrayObject
    in_vect_packed_packed_packed: cocotb.handle.LogicArrayObject
    in_vect_packed_packed_unpacked: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    in_vect_packed_unpacked_unpacked: cocotb.handle.ArrayObject[cocotb.types.Array[cocotb.types.LogicArray], cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]]
    in_vect_unpacked: cocotb.handle.ArrayObject[cocotb.types.Logic, cocotb.handle.LogicObject]
    in_vect_unpacked_unpacked_unpacked: cocotb.handle.ArrayObject[cocotb.types.Array[cocotb.types.Array[cocotb.types.Logic]], cocotb.handle.ArrayObject[cocotb.types.Array[cocotb.types.Logic], cocotb.handle.ArrayObject[cocotb.types.Logic, cocotb.handle.LogicObject]]]
    out_2d_arr: cocotb.handle.LogicArrayObject
    out_2d_arr_packed: cocotb.handle.LogicArrayObject
    out_2d_arr_unpacked: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    out_2d_vect_packed_packed: cocotb.handle.LogicArrayObject
    out_2d_vect_packed_unpacked: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    out_2d_vect_unpacked_unpacked: cocotb.handle.ArrayObject[cocotb.types.Array[cocotb.types.Logic], cocotb.handle.ArrayObject[cocotb.types.Logic, cocotb.handle.LogicObject]]
    out_3d_arr: cocotb.handle.LogicArrayObject
    out_arr: cocotb.handle.LogicArrayObject
    out_arr_packed: cocotb.handle.LogicArrayObject
    out_arr_packed_packed: cocotb.handle.LogicArrayObject
    out_arr_packed_unpacked: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    out_arr_unpacked: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    out_arr_unpacked_unpacked: cocotb.handle.ArrayObject[cocotb.types.Array[cocotb.types.LogicArray], cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]]
    out_vect_packed: cocotb.handle.LogicArrayObject
    out_vect_packed_packed_packed: cocotb.handle.LogicArrayObject
    out_vect_packed_packed_unpacked: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    out_vect_packed_unpacked_unpacked: cocotb.handle.ArrayObject[cocotb.types.Array[cocotb.types.LogicArray], cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]]
    out_vect_unpacked: cocotb.handle.ArrayObject[cocotb.types.Logic, cocotb.handle.LogicObject]
    out_vect_unpacked_unpacked_unpacked: cocotb.handle.ArrayObject[cocotb.types.Array[cocotb.types.Array[cocotb.types.Logic]], cocotb.handle.ArrayObject[cocotb.types.Array[cocotb.types.Logic], cocotb.handle.ArrayObject[cocotb.types.Logic, cocotb.handle.LogicObject]]]
