from __future__ import annotations
import cocotb.handle
import cocotb.types

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class DUT(cocotb.handle.HierarchyObject):
    A_COLUMNS_B_ROWS: cocotb.handle.LogicArrayObject
    A_ROWS: cocotb.handle.LogicArrayObject
    B_COLUMNS: cocotb.handle.LogicArrayObject
    C_DATA_WIDTH: cocotb.handle.LogicArrayObject
    DATA_WIDTH: cocotb.handle.LogicArrayObject
    a_i: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    b_i: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    c_calc: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    c_o: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    clk_i: cocotb.handle.LogicObject
    reset_i: cocotb.handle.LogicObject
    valid_i: cocotb.handle.LogicObject
    valid_o: cocotb.handle.LogicObject
    multiply: Multiply
    proc_reg: ProcReg

class Multiply(cocotb.handle.HierarchyObject):
    c_element: cocotb.handle.LogicArrayObject
    unnamedblk1: Unnamedblk1

class Unnamedblk1(cocotb.handle.HierarchyObject):
    i: cocotb.handle.LogicArrayObject
    C_ROWS: CRows

class CRows(cocotb.handle.HierarchyObject):
    unnamedblk2: Unnamedblk2

class CColumns(cocotb.handle.HierarchyObject):
    unnamedblk3: Unnamedblk3

class ProcReg(cocotb.handle.HierarchyObject):
    unnamedblk4: Unnamedblk4
    unnamedblk5: Unnamedblk5

class Unnamedblk5(cocotb.handle.HierarchyObject):
    idx: cocotb.handle.LogicArrayObject
