from __future__ import annotations
import cocotb.handle
import cocotb.types

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class MatrixMultiplier(cocotb.handle.HierarchyObject):
    clk_i: cocotb.handle.LogicObject
    reset_i: cocotb.handle.LogicObject
    valid_i: cocotb.handle.LogicObject
    valid_o: cocotb.handle.LogicObject
    a_i: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    b_i: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    c_calc: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    c_o: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    A_COLUMNS_B_ROWS: cocotb.handle.LogicArrayObject
    A_ROWS: cocotb.handle.LogicArrayObject
    B_COLUMNS: cocotb.handle.LogicArrayObject
    C_DATA_WIDTH: cocotb.handle.LogicArrayObject
    DATA_WIDTH: cocotb.handle.LogicArrayObject
