# This is an auto-generated Python module for cocotb testbench
# Generated by copra v0.1.0 at 2025-06-01 08:20:32
# Template: default
"""Auto-generated type stubs for cocotb DUT.

This file provides type hints for IDE autocompletion and static type checking.
Generated from DUT hierarchy analysis using copra.

Usage:
    from typing import cast
    from cpu_top import DutType

    @cocotb.test()
    async def test_example(dut):
        typed_dut = cast(DutType, dut)
        # Now you have full IDE support for dut.signal_name
"""

from typing import TYPE_CHECKING

from cocotb.handle import (
    HierarchyObject,
    SimHandleBase,
)

if TYPE_CHECKING:
    # Runtime implementation would be here
    pass

class CpuTop(HierarchyObject):
    """Type stub for cpu_top DUT.

    This class provides type hints for all signals in the DUT hierarchy.
    Total signals: 365
    """

    cpu_top: SimHandleBase  # Signal at path: cpu_top
    cpu_top_addr_width: SimHandleBase  # Signal at path: cpu_top.ADDR_WIDTH
    cpu_top_cache_size: SimHandleBase  # Signal at path: cpu_top.CACHE_SIZE
    cpu_top_data_width: SimHandleBase  # Signal at path: cpu_top.DATA_WIDTH
    cpu_top_num_cores: SimHandleBase  # Signal at path: cpu_top.NUM_CORES
    cpu_top_num_interrupts: SimHandleBase  # Signal at path: cpu_top.NUM_INTERRUPTS
    cpu_top_clk: SimHandleBase  # Signal at path: cpu_top.clk
    cpu_top_core_active: SimHandleBase  # Signal at path: cpu_top.core_active
    cpu_top_core_clk: SimHandleBase  # Signal at path: cpu_top.core_clk
    cpu_top_core_enable: SimHandleBase  # Signal at path: cpu_top.core_enable
    cpu_top_core_error: SimHandleBase  # Signal at path: cpu_top.core_error
    cpu_top_core_halted: SimHandleBase  # Signal at path: cpu_top.core_halted
    cpu_top_core_rst_n: SimHandleBase  # Signal at path: cpu_top.core_rst_n
    cpu_top_debug_ack: SimHandleBase  # Signal at path: cpu_top.debug_ack
    cpu_top_debug_addr: SimHandleBase  # Signal at path: cpu_top.debug_addr
    cpu_top_debug_rdata: SimHandleBase  # Signal at path: cpu_top.debug_rdata
    cpu_top_debug_req: SimHandleBase  # Signal at path: cpu_top.debug_req
    cpu_top_debug_wdata: SimHandleBase  # Signal at path: cpu_top.debug_wdata
    cpu_top_debug_we: SimHandleBase  # Signal at path: cpu_top.debug_we
    cpu_top_global_enable: SimHandleBase  # Signal at path: cpu_top.global_enable
    cpu_top_interrupt_ack: SimHandleBase  # Signal at path: cpu_top.interrupt_ack
    cpu_top_interrupt_id: SimHandleBase  # Signal at path: cpu_top.interrupt_id
    cpu_top_interrupts: SimHandleBase  # Signal at path: cpu_top.interrupts
    cpu_top_m_axi_dm_araddr: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_araddr
    cpu_top_m_axi_dm_arburst: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_arburst
    cpu_top_m_axi_dm_arcache: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_arcache
    cpu_top_m_axi_dm_arid: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_arid
    cpu_top_m_axi_dm_arlen: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_arlen
    cpu_top_m_axi_dm_arlock: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_arlock
    cpu_top_m_axi_dm_arprot: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_arprot
    cpu_top_m_axi_dm_arready: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_arready
    cpu_top_m_axi_dm_arsize: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_arsize
    cpu_top_m_axi_dm_arvalid: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_arvalid
    cpu_top_m_axi_dm_awaddr: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_awaddr
    cpu_top_m_axi_dm_awburst: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_awburst
    cpu_top_m_axi_dm_awcache: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_awcache
    cpu_top_m_axi_dm_awid: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_awid
    cpu_top_m_axi_dm_awlen: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_awlen
    cpu_top_m_axi_dm_awlock: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_awlock
    cpu_top_m_axi_dm_awprot: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_awprot
    cpu_top_m_axi_dm_awready: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_awready
    cpu_top_m_axi_dm_awsize: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_awsize
    cpu_top_m_axi_dm_awvalid: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_awvalid
    cpu_top_m_axi_dm_bid: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_bid
    cpu_top_m_axi_dm_bready: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_bready
    cpu_top_m_axi_dm_bresp: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_bresp
    cpu_top_m_axi_dm_bvalid: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_bvalid
    cpu_top_m_axi_dm_rdata: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_rdata
    cpu_top_m_axi_dm_rid: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_rid
    cpu_top_m_axi_dm_rlast: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_rlast
    cpu_top_m_axi_dm_rready: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_rready
    cpu_top_m_axi_dm_rresp: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_rresp
    cpu_top_m_axi_dm_rvalid: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_rvalid
    cpu_top_m_axi_dm_wdata: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_wdata
    cpu_top_m_axi_dm_wlast: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_wlast
    cpu_top_m_axi_dm_wready: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_wready
    cpu_top_m_axi_dm_wstrb: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_wstrb
    cpu_top_m_axi_dm_wvalid: SimHandleBase  # Signal at path: cpu_top.m_axi_dm_wvalid
    cpu_top_m_axi_if_araddr: SimHandleBase  # Signal at path: cpu_top.m_axi_if_araddr
    cpu_top_m_axi_if_arburst: SimHandleBase  # Signal at path: cpu_top.m_axi_if_arburst
    cpu_top_m_axi_if_arcache: SimHandleBase  # Signal at path: cpu_top.m_axi_if_arcache
    cpu_top_m_axi_if_arid: SimHandleBase  # Signal at path: cpu_top.m_axi_if_arid
    cpu_top_m_axi_if_arlen: SimHandleBase  # Signal at path: cpu_top.m_axi_if_arlen
    cpu_top_m_axi_if_arlock: SimHandleBase  # Signal at path: cpu_top.m_axi_if_arlock
    cpu_top_m_axi_if_arprot: SimHandleBase  # Signal at path: cpu_top.m_axi_if_arprot
    cpu_top_m_axi_if_arready: SimHandleBase  # Signal at path: cpu_top.m_axi_if_arready
    cpu_top_m_axi_if_arsize: SimHandleBase  # Signal at path: cpu_top.m_axi_if_arsize
    cpu_top_m_axi_if_arvalid: SimHandleBase  # Signal at path: cpu_top.m_axi_if_arvalid
    cpu_top_m_axi_if_awaddr: SimHandleBase  # Signal at path: cpu_top.m_axi_if_awaddr
    cpu_top_m_axi_if_awburst: SimHandleBase  # Signal at path: cpu_top.m_axi_if_awburst
    cpu_top_m_axi_if_awcache: SimHandleBase  # Signal at path: cpu_top.m_axi_if_awcache
    cpu_top_m_axi_if_awid: SimHandleBase  # Signal at path: cpu_top.m_axi_if_awid
    cpu_top_m_axi_if_awlen: SimHandleBase  # Signal at path: cpu_top.m_axi_if_awlen
    cpu_top_m_axi_if_awlock: SimHandleBase  # Signal at path: cpu_top.m_axi_if_awlock
    cpu_top_m_axi_if_awprot: SimHandleBase  # Signal at path: cpu_top.m_axi_if_awprot
    cpu_top_m_axi_if_awready: SimHandleBase  # Signal at path: cpu_top.m_axi_if_awready
    cpu_top_m_axi_if_awsize: SimHandleBase  # Signal at path: cpu_top.m_axi_if_awsize
    cpu_top_m_axi_if_awvalid: SimHandleBase  # Signal at path: cpu_top.m_axi_if_awvalid
    cpu_top_m_axi_if_bid: SimHandleBase  # Signal at path: cpu_top.m_axi_if_bid
    cpu_top_m_axi_if_bready: SimHandleBase  # Signal at path: cpu_top.m_axi_if_bready
    cpu_top_m_axi_if_bresp: SimHandleBase  # Signal at path: cpu_top.m_axi_if_bresp
    cpu_top_m_axi_if_bvalid: SimHandleBase  # Signal at path: cpu_top.m_axi_if_bvalid
    cpu_top_m_axi_if_rdata: SimHandleBase  # Signal at path: cpu_top.m_axi_if_rdata
    cpu_top_m_axi_if_rid: SimHandleBase  # Signal at path: cpu_top.m_axi_if_rid
    cpu_top_m_axi_if_rlast: SimHandleBase  # Signal at path: cpu_top.m_axi_if_rlast
    cpu_top_m_axi_if_rready: SimHandleBase  # Signal at path: cpu_top.m_axi_if_rready
    cpu_top_m_axi_if_rresp: SimHandleBase  # Signal at path: cpu_top.m_axi_if_rresp
    cpu_top_m_axi_if_rvalid: SimHandleBase  # Signal at path: cpu_top.m_axi_if_rvalid
    cpu_top_m_axi_if_wdata: SimHandleBase  # Signal at path: cpu_top.m_axi_if_wdata
    cpu_top_m_axi_if_wlast: SimHandleBase  # Signal at path: cpu_top.m_axi_if_wlast
    cpu_top_m_axi_if_wready: SimHandleBase  # Signal at path: cpu_top.m_axi_if_wready
    cpu_top_m_axi_if_wstrb: SimHandleBase  # Signal at path: cpu_top.m_axi_if_wstrb
    cpu_top_m_axi_if_wvalid: SimHandleBase  # Signal at path: cpu_top.m_axi_if_wvalid
    cpu_top_perf_branch_mispred: SimHandleBase  # Signal
    cpu_top_perf_branch_taken: SimHandleBase  # Signal
    cpu_top_perf_cache_hits: SimHandleBase  # Signal at path: cpu_top.perf_cache_hits
    cpu_top_perf_cache_misses: SimHandleBase  # Signal
    cpu_top_perf_cycle_count: SimHandleBase  # Signal at path: cpu_top.perf_cycle_count
    cpu_top_perf_instr_count: SimHandleBase  # Signal at path: cpu_top.perf_instr_count
    cpu_top_rst_n: SimHandleBase  # Signal at path: cpu_top.rst_n
    cpu_top_s_apb_paddr: SimHandleBase  # Signal at path: cpu_top.s_apb_paddr
    cpu_top_s_apb_pclk: SimHandleBase  # Signal at path: cpu_top.s_apb_pclk
    cpu_top_s_apb_penable: SimHandleBase  # Signal at path: cpu_top.s_apb_penable
    cpu_top_s_apb_prdata: SimHandleBase  # Signal at path: cpu_top.s_apb_prdata
    cpu_top_s_apb_pready: SimHandleBase  # Signal at path: cpu_top.s_apb_pready
    cpu_top_s_apb_presetn: SimHandleBase  # Signal at path: cpu_top.s_apb_presetn
    cpu_top_s_apb_psel: SimHandleBase  # Signal at path: cpu_top.s_apb_psel
    cpu_top_s_apb_pslverr: SimHandleBase  # Signal at path: cpu_top.s_apb_pslverr
    cpu_top_s_apb_pstrb: SimHandleBase  # Signal at path: cpu_top.s_apb_pstrb
    cpu_top_s_apb_pwdata: SimHandleBase  # Signal at path: cpu_top.s_apb_pwdata
    cpu_top_s_apb_pwrite: SimHandleBase  # Signal at path: cpu_top.s_apb_pwrite
    cpu_top_system_ready: SimHandleBase  # Signal at path: cpu_top.system_ready
    cpu_top_test_mode: SimHandleBase  # Signal at path: cpu_top.test_mode
    cpu_top_u_clock_gen: SimHandleBase  # Signal at path: cpu_top.u_clock_gen
    cpu_top_u_clock_gen_num_cores: SimHandleBase  # Signal
    cpu_top_u_clock_gen_clk_in: SimHandleBase  # Signal
    cpu_top_u_clock_gen_core_clk: SimHandleBase  # Signal
    cpu_top_u_clock_gen_core_enable: SimHandleBase  # Signal
    cpu_top_u_clock_gen_core_rst_n: SimHandleBase  # Signal
    cpu_top_u_clock_gen_gen_core_clocks: SimHandleBase  # Signal
    cpu_top_u_clock_gen_global_enable: SimHandleBase  # Signal
    cpu_top_u_clock_gen_rst_n_in: SimHandleBase  # Signal
    cpu_top_u_clock_gen_system_ready: SimHandleBase  # Signal
    cpu_top_u_clock_gen_test_mode: SimHandleBase  # Signal
    cpu_top_u_cpu_complex: SimHandleBase  # Signal at path: cpu_top.u_cpu_complex
    cpu_top_u_cpu_complex_addr_width: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_cache_size: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_data_width: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_num_cores: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_clk: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_active: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_branch_mispred: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_branch_taken: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_cache_hits: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_cache_misses: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_cycle_count: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_dm_ack: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_dm_addr: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_dm_rdata: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_dm_req: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_dm_wdata: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_dm_we: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_enable: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_error: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_halted: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_if_ack: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_if_addr: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_if_rdata: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_if_req: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_core_instr_count: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_debug_ack: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_debug_addr: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_debug_rdata: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_debug_req: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_debug_wdata: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_debug_we: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_gen_cpu_cores: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_interrupt_ack: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_interrupt_id: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_interrupts: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_araddr: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_arburst: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_arcache: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_arid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_arlen: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_arlock: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_arprot: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_arready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_arsize: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_arvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_awaddr: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_awburst: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_awcache: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_awid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_awlen: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_awlock: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_awprot: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_awready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_awsize: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_awvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_bid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_bready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_bresp: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_bvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_rdata: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_rid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_rlast: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_rready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_rresp: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_rvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_wdata: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_wlast: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_wready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_wstrb: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_dm_wvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_araddr: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_arburst: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_arcache: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_arid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_arlen: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_arlock: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_arprot: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_arready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_arsize: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_arvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_awaddr: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_awburst: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_awcache: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_awid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_awlen: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_awlock: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_awprot: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_awready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_awsize: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_awvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_bid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_bready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_bresp: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_bvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_rdata: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_rid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_rlast: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_rready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_rresp: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_rvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_wdata: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_wlast: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_wready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_wstrb: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_m_axi_if_wvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_perf_branch_mispred: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_perf_branch_taken: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_perf_cache_hits: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_perf_cache_misses: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_perf_cycle_count: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_perf_instr_count: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_rst_n: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_addr_width: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_data_width: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_num_cores: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_clk: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_core_ack: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_core_addr: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_core_rdata: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_core_req: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_core_wdata: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_core_we: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_current_core: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_araddr: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_arburst: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_arcache: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_arid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_arlen: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_arlock: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_arprot: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_arready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_arsize: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_arvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_awaddr: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_awburst: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_awcache: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_awid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_awlen: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_awlock: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_awprot: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_awready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_awsize: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_awvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_bid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_bready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_bresp: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_bvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_rdata: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_rid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_rlast: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_rready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_rresp: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_rvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_wdata: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_wlast: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_wready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_wstrb: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_m_axi_wvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_next_core: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_dm_arbiter_rst_n: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_addr_width: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_data_width: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_num_cores: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_clk: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_core_ack: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_core_addr: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_core_rdata: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_core_req: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_current_core: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_araddr: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_arburst: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_arcache: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_arid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_arlen: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_arlock: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_arprot: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_arready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_arsize: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_arvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_awaddr: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_awburst: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_awcache: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_awid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_awlen: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_awlock: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_awprot: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_awready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_awsize: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_awvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_bid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_bready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_bresp: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_bvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_rdata: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_rid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_rlast: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_rready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_rresp: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_rvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_wdata: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_wlast: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_wready: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_wstrb: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_m_axi_wvalid: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_next_core: SimHandleBase  # Signal
    cpu_top_u_cpu_complex_u_if_arbiter_rst_n: SimHandleBase  # Signal
    cpu_top_u_csr_block: SimHandleBase  # Signal at path: cpu_top.u_csr_block
    cpu_top_u_csr_block_addr_width: SimHandleBase  # Signal
    cpu_top_u_csr_block_csr_core_status: SimHandleBase  # Signal
    cpu_top_u_csr_block_csr_perf_branch_mis: SimHandleBase  # Signal
    cpu_top_u_csr_block_csr_perf_branch_tkn: SimHandleBase  # Signal
    cpu_top_u_csr_block_csr_perf_cache_hits: SimHandleBase  # Signal
    cpu_top_u_csr_block_csr_perf_cache_miss: SimHandleBase  # Signal
    cpu_top_u_csr_block_csr_perf_cycles: SimHandleBase  # Signal
    cpu_top_u_csr_block_csr_perf_instrs: SimHandleBase  # Signal
    cpu_top_u_csr_block_data_width: SimHandleBase  # Signal
    cpu_top_u_csr_block_num_cores: SimHandleBase  # Signal
    cpu_top_u_csr_block_clk: SimHandleBase  # Signal at path: cpu_top.u_csr_block.clk
    cpu_top_u_csr_block_control_reg: SimHandleBase  # Signal
    cpu_top_u_csr_block_core_active: SimHandleBase  # Signal
    cpu_top_u_csr_block_core_error: SimHandleBase  # Signal
    cpu_top_u_csr_block_core_halted: SimHandleBase  # Signal
    cpu_top_u_csr_block_paddr: SimHandleBase  # Signal
    cpu_top_u_csr_block_penable: SimHandleBase  # Signal
    cpu_top_u_csr_block_perf_branch_mispred: SimHandleBase  # Signal
    cpu_top_u_csr_block_perf_branch_taken: SimHandleBase  # Signal
    cpu_top_u_csr_block_perf_cache_hits: SimHandleBase  # Signal
    cpu_top_u_csr_block_perf_cache_misses: SimHandleBase  # Signal
    cpu_top_u_csr_block_perf_cycle_count: SimHandleBase  # Signal
    cpu_top_u_csr_block_perf_instr_count: SimHandleBase  # Signal
    cpu_top_u_csr_block_prdata: SimHandleBase  # Signal
    cpu_top_u_csr_block_pready: SimHandleBase  # Signal
    cpu_top_u_csr_block_psel: SimHandleBase  # Signal at path: cpu_top.u_csr_block.psel
    cpu_top_u_csr_block_pslverr: SimHandleBase  # Signal
    cpu_top_u_csr_block_pstrb: SimHandleBase  # Signal
    cpu_top_u_csr_block_pwdata: SimHandleBase  # Signal
    cpu_top_u_csr_block_pwrite: SimHandleBase  # Signal
    cpu_top_u_csr_block_rst_n: SimHandleBase  # Signal


# Type alias for the main DUT
DutType = CpuTop

# Runtime implementation would include actual signal handling
# This is a stub file for type checking purposes
