# This is an auto-generated Python module for cocotb testbench
# Generated by copra v0.1.0 at 2025-06-01 08:34:48
# Template: default
"""Auto-generated type stubs for cocotb DUT.

This file provides type hints for IDE autocompletion and static type checking.
Generated from DUT hierarchy analysis using copra.

Usage:
    from typing import cast
    from cpu_top import DutType

    @cocotb.test()
    async def test_example(dut):
        typed_dut = cast(DutType, dut)
        # Now you have full IDE support for dut.signal_name
"""

from typing import TYPE_CHECKING

from cocotb.handle import (
    HierarchyObject,
    SimHandleBase,
)

if TYPE_CHECKING:
    # Runtime implementation would be here
    pass

class CpuTop(HierarchyObject):
    """Type stub for cpu_top DUT.

    This class provides type hints for all signals in the DUT hierarchy.
    Total signals: 2
    """

    cpu_top: SimHandleBase  # Signal at path: cpu_top
    cpu_top_clk: SimHandleBase  # Signal at path: cpu_top.clk


# Type alias for the main DUT
DutType = CpuTop

# Runtime implementation would include actual signal handling
# This is a stub file for type checking purposes
