from __future__ import annotations
import cocotb.handle
import cocotb.types
from typing import overload, Literal

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class Dff(cocotb.handle.HierarchyObject):
    clk: cocotb.handle.LogicObject
    d: cocotb.handle.LogicObject
    q: cocotb.handle.LogicObject

    @overload
    def __getitem__(self, name: Literal["_reset_n"]) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal["clk"]) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal["d"]) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal["!special!\\\\"]) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal["q"]) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...
