from __future__ import annotations
import cocotb.handle
import cocotb.types

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class Dff(cocotb.handle.HierarchyObject):
    clk: cocotb.handle.LogicObject
    d: cocotb.handle.LogicObject
    q: cocotb.handle.LogicObject
