from __future__ import annotations
import cocotb.handle
import cocotb.types

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class DUT(cocotb.handle.HierarchyObject):
    clk: cocotb.handle.LogicObject
    # clk.value: cocotb.types.Logic
    d: cocotb.handle.LogicObject
    # d.value: cocotb.types.Logic
    q: cocotb.handle.LogicObject
    # q.value: cocotb.types.Logic
