"""Version information for copra."""

# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause
# This file is auto-generated by setuptools-scm
from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("copra")
except PackageNotFoundError:
    # package is not installed
    __version__ = "unknown"
