"""Version information for copra."""

# This file is auto-generated by setuptools-scm
from importlib.metadata import version, PackageNotFoundError

try:
    __version__ = version("copra")
except PackageNotFoundError:
    # package is not installed
    __version__ = "0.0.0+unknown"
